name = "Lemon Packet"
author = "小柠檬lemon酱"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e908589afadaa133c499ccdc76e3fb4f322e3d77ea29910198aed71d422e60b4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
