name = "Lemon Packet"
author = "小柠檬lemon酱"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19994c8f97ef86534de64de9e78ddcc64a4219f6dd58ac06d1ab27640c65f268"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
