name = "Lemon Packet"
author = "小柠檬lemon酱"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1556ddc1ff956ed8583c8ee3efe5830ddef4b6366446dce63ba7c4d725b7443"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
